name: ARGOCD GITOPS CREATE

on:
  create

jobs:
  Test: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout ArgoCD GitOps repo
        uses: actions/checkout@master
        with:
          repository: devops-systems/argocd-gitops
          ref: 'main'
          token:  ${{ secrets.GITOPS_TOKEN }}
          path: 'gitops'
      - name: Generate variables                 
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)" >> $GITHUB_ENV
          echo "BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Generate file 
        working-directory: gitops
        run: |
          curl -sfL -o /usr/local/bin/kyml https://github.com/frigus02/kyml/releases/download/v20210610/kyml_20210610_linux_amd64 && chmod +x /usr/local/bin/kyml
          cat templates/argocd_gitops_features.yaml | kyml tmpl -e REPO -e BRANCH -e IMAGE_TAG | tee apps-features/$REPO-$BRANCH.yaml
      - name: Commit & Push changes
        working-directory: gitops
        run: |
          git add .
          git commit -m "$(date)"
          git push
