name: ARGOCD GITOPS CREATE

on:
  create

jobs:
  Test: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout ArgoCD GitOps repo
        uses: actions/checkout@master
        with:
          repository: devops-systems/argocd-gitops
          ref: 'main'
          token:  ${{ secrets.GITOPS_TOKEN }}
          path: 'gitops'
      - name: Generate variables                 
        run: |
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)" >> $GITHUB_ENV
          echo "BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
      - name: Generate file 
        working-directory: gitops
        run: |
          envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < templates/argocd_gitops_features.yaml > apps-features/$REPO-$BRANCH.yaml
          cat apps-features/$REPO-$BRANCH.yaml
      - name: Commit & Push changes to ArgoCD GitOps
        working-directory: gitops
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.GITOPS_EMAIL }}"
          git add .
          git commit -m "$REPO $BRANCH $(date)"
          git push
