name: ARGOCD GITOPS CREATE

on:
  create

jobs:
  Test: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout ArgoCD GitOps repo
        uses: actions/checkout@master
        with:
          repository: devops-systems/argocd-gitops
          ref: 'main'
          token:  ${{ secrets.GITOPS_TOKEN }}
          path: 'gitops'
      - name: Generate variables                 
        run: |
          if [ $GITHUB_REF_NAME == 'main' ] 
          then
            echo "ARGOCD_APPLICATION_TEMP_FILE=templates/argocd_gitops_prod.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps-prod" >> $GITHUB_ENV
          elif [ $GITHUB_REF_NAME == 'dev' ]
          then
            echo "ARGOCD_APPLICATION_TEMP_FILE=templates/argocd_gitops_dev.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps-dev" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "ARGOCD_APPLICATION_TEMP_FILE=templates/argocd_gitops_features.yaml" >> $GITHUB_ENV
            echo "ARGOCD_APPLICATION_FOLDER=apps-features" >> $GITHUB_ENV
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi
          echo "REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)" >> $GITHUB_ENV # cutting repo name
          export BRANCH=${GITHUB_REF_NAME//[^[:alnum:]]/} # remove special characters
          echo "BRANCH=${BRANCH,,}" >> $GITHUB_ENV # move in lowercase
      - name: Generate file 
        working-directory: gitops
        run: |
          envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < $ARGOCD_APPLICATION_TEMP_FILE > $ARGOCD_APPLICATION_FOLDER/$REPO-$BRANCH.yaml
          cat $ARGOCD_APPLICATION_FOLDER/$REPO-$BRANCH.yaml
      - name: Commit & Push changes to ArgoCD GitOps
        working-directory: gitops
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.GITOPS_EMAIL }}"
          git add $ARGOCD_APPLICATION_FOLDER/$REPO-$BRANCH.yaml
          git commit -m "GitHub Actions Bot - $(date)"
          git push
