name: ARGOCD GITOPS

on:
  branch_protection_rule:
    types: [created, deleted]

jobs:
  Test: 
    runs-on: 'ubuntu-latest'
    steps:
      - name: Get envs                 
        run: |
          echo $GITHUB_ENV
